name: ğŸš€ Publish package to Pypi ğŸ

on:
  push:
    branches: [master]
    paths: [VERSION]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '2.7', '3.6' , '3.7' , '3.8' , '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setting Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running CLI
        run: python setup.py install

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Add --exit-zero to throw all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setting Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.*'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package
        run: python setup.py install
      - name: Running tests
        run: python -c "from dome9 import Dome9;d9 = Dome9('username','password')" # Pending tests

  deploy:
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: âš™ï¸ Install pypa/build  # Unnecessary
        run: python -m pip install build --user
      - name: âš™ï¸ Build Wheel (wheel) and Source Tarball (sdist)
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: ğŸš€ğŸ§ª Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: ğŸš€ğŸ’¥ Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
    